name: ChunkClaim
main: com.github.schmidtbochum.chunkclaim.ChunkClaim
version: 1.1.0
author: schmidtbochum
softdepend: [Multiverse-Core]
description: >
             Chunk Protection
commands:
  chunk:
    description: Displays information about the chunk.
    usage: "/chunk [credits|abandon|trust|untrust]"
permissions:
  chunkclaim.claim:
    description: Claim chunks.
  chunkclaim.admin:
    description: Ignore chunk ownership, manage chunks.
    default: op