name: ChunkClaim
main: com.kmaismith.chunkclaim.ChunkClaim
version: 2.0-SNAPSHOT
author: schmidtbochum & kMaiSmith
softdepend: [Multiverse-Core]
description: >
             Simple Chunk Protection with Forge mod support
commands:
  chunk:
    description: Displays information about the chunk.
    usage: "/chunk [credits|abandon|trust|untrust|list]"
permissions:
  chunkclaim.claim:
    description: Claim chunks.
  chunkclaim.admin:
    description: Ignore chunk ownership, manage chunks.
    default: op